### PR TITLE
Attempt on fixing abort events for fetch()

### LINKED ISSUE #41: fetch + pretender.js + AbortController - does not reject fetch() with AbortError
`load` event fires before `abort` thus making impossible to use with `fetch` + `pretender.js` + `AbortController` to signal fetch `abort()`.

https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/src/fake-xml-http-request.js#L305 <-- this trigger ready state change update

Which ends up here:  https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/src/fake-xml-http-request.js#L382

But this it is missing "this.aborted" check and blindly dispatches "load" event.

According to spec: https://xhr.spec.whatwg.org/#event-xhr-load <-- load should be edmitted only on success.

**Solution 1**
So for testing purposes I wrapped "load" event dispatch into "`if (!this.aborted)`" and I get proper AbortedError from "fetch" and everything.

**Solution 2**

Move https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/fake_xml_http_request.js#L317 - before https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/fake_xml_http_request.js#L310

But this probably breaks other behaviour, ie checking readyState in your `abort` event callback.

### PR DESCRIPTION
**Pull request by raido**
Resolves #41 hopefully.

### CODE REVIEW

File: src/fake-xml-http-request.js [hunk 1]
```diff
@@ -381,8 +380,8 @@ var FakeXMLHttpRequestProto = {
 
     if (this.readyState == FakeXMLHttpRequest.DONE) {
       this.dispatchEvent(new _Event("load", false, false, this));
-      this.dispatchEvent(new _Event("loadend", false, false, this));
     }
+    this.dispatchEvent(new _Event("loadend", false, false, this));
```
Comment (raido) [inline src/fake-xml-http-request.js]: This is actually bug now, because every time  _readyStateChange is called this "loadend" gets dispatched. For example FakeXMLHttpRequest.OPEN is dispatched and follows with `loadend`.

**Comment by raido** [comment]
@trek

**Comment by BenPatterson2** [comment]
any chance of releasing v2.0.1 to npm? I think I need this fix
